### PR TITLE
fix #104 use absolute node_modules path for npm dependencies

### LINKED ISSUE #104: Support npm v3+ non nested node_modules
Origin of non nested node_modules in npm:
- https://github.com/nodejs/node-v0.x-archive/issues/6960

Other possible workaround:
- https://github.com/npm/npm/issues/9809

### PR DESCRIPTION
**Pull request by hthetiot**
see #104

### CODE REVIEW

**Comment by hthetiot** [comment]
@marchant Yes just added engine and engineStrict to package.json
For reference: http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

**Comment by hthetiot** [comment]
Not that simple, working on edge case

**Comment by hthetiot** [comment]
@marchant the problem is that their is no way to make the difference from a relative module and a "root" module.

Currently, on master branch, require() is loading the module in the "node_modules" of the current module and process module with or without "./" the same way my removing "./"

Meaning from a module "a" calling require("b") or require("./b") will result "node_modules/a/node_modules/b".

The issue with this is that if you need to load a module that is not a sub-module you need to specify the full path in order to support npm 3+ . (Example weak-map in collections)

What I'm proposing is to match the AMD standard, and load module as submodule only if relative.

Example:
1. calling require("./b")  from module "a" will result "node_modules/a/node_modules/b".
2. calling require("b") from module "a" will result "node_modules/b".

**Comment by kriskowal** [comment]
My solution to supporting npm version 3 in my fork turned out to be pretty simple, but not what I thought. The _npmVersion is not useful. Assuming a flat structure (all packages installed in the root package) when _args is present in package.json does the trick.

https://github.com/gutentags/system/pull/10

**Comment by hthetiot** [comment]
@kishores I will check that. Thx.

**Pull request closed without merging**
